[package]
name = "spirv"
version = "0.1.1"
authors = ["Chris Chamberlain <c.chamberlain@iinet.net.au>"]
license = "MIT"
description = "SPIR-V parser (abandoned)"
repository = "https://github.com/neon64/spirv"

[dependencies]
libc = "*"
