use instruction::data::*;
use spirv::Op;

#[derive(Debug)]
pub enum Instruction<'a> {
    Nop,
    Undef(&'a OpUndef),
    Source(&'a OpSource),
    SourceExtension(&'a OpSourceExtension),
    Name(&'a OpName),
    MemberName(&'a OpMemberName),
    String(&'a OpString),
    Line(&'a OpLine),
    DecorationGroup(&'a OpDecorationGroup),
    Decorate(&'a OpDecorate),
    MemberDecorate(&'a OpMemberDecorate),
    GroupDecorate(&'a OpGroupDecorate),
    GroupMemberDecorate(&'a OpGroupMemberDecorate),
    Extension(&'a OpExtension),
    ExtInstImport(&'a OpExtInstImport),
    ExtInst(&'a OpExtInst),
    MemoryModel(&'a OpMemoryModel),
    EntryPoint(&'a OpEntryPoint),
    ExecutionMode(&'a OpExecutionMode),
    CompileFlag(&'a OpCompileFlag),
    TypeVoid(&'a OpTypeVoid),
    TypeBool(&'a OpTypeBool),
    TypeInt(&'a OpTypeInt),
    TypeFloat(&'a OpTypeFloat),
    TypeVector(&'a OpTypeVector),
    TypeMatrix(&'a OpTypeMatrix),
    TypeSampler(&'a OpTypeSampler),
    TypeFilter(&'a OpTypeFilter),
    TypeArray(&'a OpTypeArray),
    TypeRuntimeArray(&'a OpTypeRuntimeArray),
    TypeStruct(&'a OpTypeStruct),
    TypeOpaque(&'a OpTypeOpaque),
    TypePointer(&'a OpTypePointer),
    TypeFunction(&'a OpTypeFunction),
    TypeEvent(&'a OpTypeEvent),
    TypeDeviceEvent(&'a OpTypeDeviceEvent),
    TypeReserveId(&'a OpTypeReserveId),
    TypeQueue(&'a OpTypeQueue),
    TypePipe(&'a OpTypePipe),
    ConstantTrue(&'a OpConstantTrue),
    ConstantFalse(&'a OpConstantFalse),
    Constant(&'a OpConstant),
    ConstantComposite(&'a OpConstantComposite),
    ConstantSampler(&'a OpConstantSampler),
    ConstantNullPointer(&'a OpConstantNullPointer),
    ConstantNullObject(&'a OpConstantNullObject),
    SpecConstantTrue(&'a OpSpecConstantTrue),
    SpecConstantFalse(&'a OpSpecConstantFalse),
    SpecConstant(&'a OpSpecConstant),
    SpecConstantComposite(&'a OpSpecConstantComposite),
    Variable(&'a OpVariable),
    VariableArray(&'a OpVariableArray),
    Load(&'a OpLoad),
    Store(&'a OpStore),
    CopyMemory(&'a OpCopyMemory),
    CopyMemorySized(&'a OpCopyMemorySized),
    AccessChain(&'a OpAccessChain),
    InBoundsAccessChain(&'a OpInBoundsAccessChain),
    ArrayLength(&'a OpArrayLength),
    ImagePointer(&'a OpImagePointer),
    GenericPtrMemSemantics(&'a OpGenericPtrMemSemantics),
    Function(&'a OpFunction),
    FunctionParameter(&'a OpFunctionParameter),
    FunctionEnd(&'a OpFunctionEnd),
    FunctionCall(&'a OpFunctionCall),
    Sampler(&'a OpSampler),
    TextureSample(&'a OpTextureSample),
    TextureSampleDref(&'a OpTextureSampleDref),
    TextureSampleLod(&'a OpTextureSampleLod),
    TextureSampleProj(&'a OpTextureSampleProj),
    TextureSampleGrad(&'a OpTextureSampleGrad),
    TextureSampleOffset(&'a OpTextureSampleOffset),
    TextureSampleProjLod(&'a OpTextureSampleProjLod),
    TextureSampleProjGrad(&'a OpTextureSampleProjGrad),
    TextureSampleLodOffset(&'a OpTextureSampleLodOffset),
    TextureSampleProjOffset(&'a OpTextureSampleProjOffset),
    TextureSampleGradOffset(&'a OpTextureSampleGradOffset),
    TextureSampleProjLodOffset(&'a OpTextureSampleProjLodOffset),
    TextureSampleProjGradOffset(&'a OpTextureSampleProjGradOffset),
    TextureFetchTexelLod(&'a OpTextureFetchTexelLod),
    TextureFetchTexelOffset(&'a OpTextureFetchTexelOffset),
    TextureFetchSample(&'a OpTextureFetchSample),
    TextureFetchTexel(&'a OpTextureFetchTexel),
    TextureGather(&'a OpTextureGather),
    TextureGatherOffset(&'a OpTextureGatherOffset),
    TextureGatherOffsets(&'a OpTextureGatherOffsets),
    TextureQuerySizeLod(&'a OpTextureQuerySizeLod),
    TextureQuerySize(&'a OpTextureQuerySize),
    TextureQueryLod(&'a OpTextureQueryLod),
    TextureQueryLevels(&'a OpTextureQueryLevels),
    TextureQuerySamples(&'a OpTextureQuerySamples),
    ConvertFToU(&'a OpConvertFToU),
    ConvertFToS(&'a OpConvertFToS),
    ConvertSToF(&'a OpConvertSToF),
    ConvertUToF(&'a OpConvertUToF),
    UConvert(&'a OpUConvert),
    SConvert(&'a OpSConvert),
    FConvert(&'a OpFConvert),
    ConvertPtrToU(&'a OpConvertPtrToU),
    ConvertUToPtr(&'a OpConvertUToPtr),
    PtrCastToGeneric(&'a OpPtrCastToGeneric),
    GenericCastToPtr(&'a OpGenericCastToPtr),
    Bitcast(&'a OpBitcast),
    GenericCastToPtrExplicit(&'a OpGenericCastToPtrExplicit),
    SatConvertSToU(&'a OpSatConvertSToU),
    SatConvertUToS(&'a OpSatConvertUToS),
    VectorExtractDynamic(&'a OpVectorExtractDynamic),
    VectorInsertDynamic(&'a OpVectorInsertDynamic),
    VectorShuffle(&'a OpVectorShuffle),
    CompositeConstruct(&'a OpCompositeConstruct),
    CompositeExtract(&'a OpCompositeExtract),
    CompositeInsert(&'a OpCompositeInsert),
    CopyObject(&'a OpCopyObject),
    Transpose(&'a OpTranspose),
    SNegate(&'a OpSNegate),
    FNegate(&'a OpFNegate),
    Not(&'a OpNot),
    IAdd(&'a OpIAdd),
    FAdd(&'a OpFAdd),
    ISub(&'a OpISub),
    FSub(&'a OpFSub),
    IMul(&'a OpIMul),
    FMul(&'a OpFMul),
    UDiv(&'a OpUDiv),
    SDiv(&'a OpSDiv),
    FDiv(&'a OpFDiv),
    UMod(&'a OpUMod),
    SRem(&'a OpSRem),
    SMod(&'a OpSMod),
    FRem(&'a OpFRem),
    FMod(&'a OpFMod),
    VectorTimesScalar(&'a OpVectorTimesScalar),
    MatrixTimesScalar(&'a OpMatrixTimesScalar),
    VectorTimesMatrix(&'a OpVectorTimesMatrix),
    MatrixTimesVector(&'a OpMatrixTimesVector),
    MatrixTimesMatrix(&'a OpMatrixTimesMatrix),
    OuterProduct(&'a OpOuterProduct),
    Dot(&'a OpDot),
    ShiftRightLogical(&'a OpShiftRightLogical),
    ShiftRightArithmetic(&'a OpShiftRightArithmetic),
    ShiftLeftLogical(&'a OpShiftLeftLogical),
    BitwiseOr(&'a OpBitwiseOr),
    BitwiseXor(&'a OpBitwiseXor),
    BitwiseAnd(&'a OpBitwiseAnd),
    Any(&'a OpAny),
    All(&'a OpAll),
    IsNan(&'a OpIsNan),
    IsInf(&'a OpIsInf),
    IsFinite(&'a OpIsFinite),
    IsNormal(&'a OpIsNormal),
    SignBitSet(&'a OpSignBitSet),
    LessOrGreater(&'a OpLessOrGreater),
    Ordered(&'a OpOrdered),
    Unordered(&'a OpUnordered),
    LogicalOr(&'a OpLogicalOr),
    LogicalXor(&'a OpLogicalXor),
    LogicalAnd(&'a OpLogicalAnd),
    Select(&'a OpSelect),
    IEqual(&'a OpIEqual),
    FOrdEqual(&'a OpFOrdEqual),
    FUnordEqual(&'a OpFUnordEqual),
    INotEqual(&'a OpINotEqual),
    FOrdNotEqual(&'a OpFOrdNotEqual),
    FUnordNotEqual(&'a OpFUnordNotEqual),
    ULessThan(&'a OpULessThan),
    SLessThan(&'a OpSLessThan),
    FOrdLessThan(&'a OpFOrdLessThan),
    FUnordLessThan(&'a OpFUnordLessThan),
    UGreaterThan(&'a OpUGreaterThan),
    SGreaterThan(&'a OpSGreaterThan),
    FOrdGreaterThan(&'a OpFOrdGreaterThan),
    FUnordGreaterThan(&'a OpFUnordGreaterThan),
    ULessThanEqual(&'a OpULessThanEqual),
    SLessThanEqual(&'a OpSLessThanEqual),
    FOrdLessThanEqual(&'a OpFOrdLessThanEqual),
    FUnordLessThanEqual(&'a OpFUnordLessThanEqual),
    UGreaterThanEqual(&'a OpUGreaterThanEqual),
    SGreaterThanEqual(&'a OpSGreaterThanEqual),
    FOrdGreaterThanEqual(&'a OpFOrdGreaterThanEqual),
    FUnordGreaterThanEqual(&'a OpFUnordGreaterThanEqual),
    DPdx(&'a OpDPdx),
    DPdy(&'a OpDPdy),
    Fwidth(&'a OpFwidth),
    DPdxFine(&'a OpDPdxFine),
    DPdyFine(&'a OpDPdyFine),
    FwidthFine(&'a OpFwidthFine),
    DPdxCoarse(&'a OpDPdxCoarse),
    DPdyCoarse(&'a OpDPdyCoarse),
    FwidthCoarse(&'a OpFwidthCoarse),
    Phi(&'a OpPhi),
    LoopMerge(&'a OpLoopMerge),
    SelectionMerge(&'a OpSelectionMerge),
    Label(&'a OpLabel),
    Branch(&'a OpBranch),
    BranchConditional(&'a OpBranchConditional),
    Switch(&'a OpSwitch),
    Kill(&'a OpKill),
    Return(&'a OpReturn),
    ReturnValue(&'a OpReturnValue),
    Unreachable(&'a OpUnreachable),
    LifetimeStart(&'a OpLifetimeStart),
    LifetimeStop(&'a OpLifetimeStop),
    AtomicInit(&'a OpAtomicInit),
    AtomicLoad(&'a OpAtomicLoad),
    AtomicStore(&'a OpAtomicStore),
    AtomicExchange(&'a OpAtomicExchange),
    AtomicCompareExchange(&'a OpAtomicCompareExchange),
    AtomicCompareExchangeWeak(&'a OpAtomicCompareExchangeWeak),
    AtomicIIncrement(&'a OpAtomicIIncrement),
    AtomicIDecrement(&'a OpAtomicIDecrement),
    AtomicIAdd(&'a OpAtomicIAdd),
    AtomicISub(&'a OpAtomicISub),
    AtomicUMin(&'a OpAtomicUMin),
    AtomicUMax(&'a OpAtomicUMax),
    AtomicAnd(&'a OpAtomicAnd),
    AtomicOr(&'a OpAtomicOr),
    AtomicXor(&'a OpAtomicXor),
    AtomicIMin(&'a OpAtomicIMin),
    AtomicIMax(&'a OpAtomicIMax),
    EmitVertex(&'a OpEmitVertex),
    EndPrimitive(&'a OpEndPrimitive),
    EmitStreamVertex(&'a OpEmitStreamVertex),
    EndStreamPrimitive(&'a OpEndStreamPrimitive),
    ControlBarrier(&'a OpControlBarrier),
    MemoryBarrier(&'a OpMemoryBarrier),
    AsyncGroupCopy(&'a OpAsyncGroupCopy),
    WaitGroupEvents(&'a OpWaitGroupEvents),
    GroupAll(&'a OpGroupAll),
    GroupAny(&'a OpGroupAny),
    GroupBroadcast(&'a OpGroupBroadcast),
    GroupIAdd(&'a OpGroupIAdd),
    GroupFAdd(&'a OpGroupFAdd),
    GroupFMin(&'a OpGroupFMin),
    GroupUMin(&'a OpGroupUMin),
    GroupSMin(&'a OpGroupSMin),
    GroupFMax(&'a OpGroupFMax),
    GroupUMax(&'a OpGroupUMax),
    GroupSMax(&'a OpGroupSMax),
    EnqueueMarker(&'a OpEnqueueMarker),
    EnqueueKernel(&'a OpEnqueueKernel),
    GetKernelNDrangeSubGroupCount(&'a OpGetKernelNDrangeSubGroupCount),
    GetKernelNDrangeMaxSubGroupSize(&'a OpGetKernelNDrangeMaxSubGroupSize),
    GetKernelWorkGroupSize(&'a OpGetKernelWorkGroupSize),
    GetKernelPreferredWorkGroupSizeMultiple(&'a OpGetKernelPreferredWorkGroupSizeMultiple),
    RetainEvent(&'a OpRetainEvent),
    ReleaseEvent(&'a OpReleaseEvent),
    CreateUserEvent(&'a OpCreateUserEvent),
    IsValidEvent(&'a OpIsValidEvent),
    SetUserEventStatus(&'a OpSetUserEventStatus),
    CaptureEventProfilingInfo(&'a OpCaptureEventProfilingInfo),
    GetDefaultQueue(&'a OpGetDefaultQueue),
    BuildNDRange(&'a OpBuildNDRange),
    ReadPipe(&'a OpReadPipe),
    WritePipe(&'a OpWritePipe),
    ReservedReadPipe(&'a OpReservedReadPipe),
    ReservedWritePipe(&'a OpReservedWritePipe),
    ReserveReadPipePackets(&'a OpReserveReadPipePackets),
    ReserveWritePipePackets(&'a OpReserveWritePipePackets),
    CommitReadPipe(&'a OpCommitReadPipe),
    CommitWritePipe(&'a OpCommitWritePipe),
    IsValidReserveId(&'a OpIsValidReserveId),
    GetNumPipePackets(&'a OpGetNumPipePackets),
    GetMaxPipePackets(&'a OpGetMaxPipePackets),
    GroupReserveReadPipePackets(&'a OpGroupReserveReadPipePackets),
    GroupReserveWritePipePackets(&'a OpGroupReserveWritePipePackets),
    GroupCommitReadPipe(&'a OpGroupCommitReadPipe),
    GroupCommitWritePipe(&'a OpGroupCommitWritePipe)
}

impl<'a> Instruction<'a> {
    pub unsafe fn from_opcode_and_ptr(opcode: Op, ptr: *const u32) -> Self {
        match opcode {
            Op::OpNop => Instruction::Nop,
            Op::OpUndef => Instruction::Undef(&*(ptr as *const _)),
            Op::OpSource => Instruction::Source(&*(ptr as *const _)),
            Op::OpSourceExtension => Instruction::SourceExtension(&*(ptr as *const _)),
            Op::OpName => Instruction::Name(&*(ptr as *const _)),
            Op::OpMemberName => Instruction::MemberName(&*(ptr as *const _)),
            Op::OpString => Instruction::String(&*(ptr as *const _)),
            Op::OpLine => Instruction::Line(&*(ptr as *const _)),
            Op::OpDecorationGroup => Instruction::DecorationGroup(&*(ptr as *const _)),
            Op::OpDecorate => Instruction::Decorate(&*(ptr as *const _)),
            Op::OpMemberDecorate => Instruction::MemberDecorate(&*(ptr as *const _)),
            Op::OpGroupDecorate => Instruction::GroupDecorate(&*(ptr as *const _)),
            Op::OpGroupMemberDecorate => Instruction::GroupMemberDecorate(&*(ptr as *const _)),
            Op::OpExtension => Instruction::Extension(&*(ptr as *const _)),
            Op::OpExtInstImport => Instruction::ExtInstImport(&*(ptr as *const _)),
            Op::OpExtInst => Instruction::ExtInst(&*(ptr as *const _)),
            Op::OpMemoryModel => Instruction::MemoryModel(&*(ptr as *const _)),
            Op::OpEntryPoint => Instruction::EntryPoint(&*(ptr as *const _)),
            Op::OpExecutionMode => Instruction::ExecutionMode(&*(ptr as *const _)),
            Op::OpCompileFlag => Instruction::CompileFlag(&*(ptr as *const _)),
            Op::OpTypeVoid => Instruction::TypeVoid(&*(ptr as *const _)),
            Op::OpTypeBool => Instruction::TypeBool(&*(ptr as *const _)),
            Op::OpTypeInt => Instruction::TypeInt(&*(ptr as *const _)),
            Op::OpTypeFloat => Instruction::TypeFloat(&*(ptr as *const _)),
            Op::OpTypeVector => Instruction::TypeVector(&*(ptr as *const _)),
            Op::OpTypeMatrix => Instruction::TypeMatrix(&*(ptr as *const _)),
            Op::OpTypeSampler => Instruction::TypeSampler(&*(ptr as *const _)),
            Op::OpTypeFilter => Instruction::TypeFilter(&*(ptr as *const _)),
            Op::OpTypeArray => Instruction::TypeArray(&*(ptr as *const _)),
            Op::OpTypeRuntimeArray => Instruction::TypeRuntimeArray(&*(ptr as *const _)),
            Op::OpTypeStruct => Instruction::TypeStruct(&*(ptr as *const _)),
            Op::OpTypeOpaque => Instruction::TypeOpaque(&*(ptr as *const _)),
            Op::OpTypePointer => Instruction::TypePointer(&*(ptr as *const _)),
            Op::OpTypeFunction => Instruction::TypeFunction(&*(ptr as *const _)),
            Op::OpTypeEvent => Instruction::TypeEvent(&*(ptr as *const _)),
            Op::OpTypeDeviceEvent => Instruction::TypeDeviceEvent(&*(ptr as *const _)),
            Op::OpTypeReserveId => Instruction::TypeReserveId(&*(ptr as *const _)),
            Op::OpTypeQueue => Instruction::TypeQueue(&*(ptr as *const _)),
            Op::OpTypePipe => Instruction::TypePipe(&*(ptr as *const _)),
            Op::OpConstantTrue => Instruction::ConstantTrue(&*(ptr as *const _)),
            Op::OpConstantFalse => Instruction::ConstantFalse(&*(ptr as *const _)),
            Op::OpConstant => Instruction::Constant(&*(ptr as *const _)),
            Op::OpConstantComposite => Instruction::ConstantComposite(&*(ptr as *const _)),
            Op::OpConstantSampler => Instruction::ConstantSampler(&*(ptr as *const _)),
            Op::OpConstantNullPointer => Instruction::ConstantNullPointer(&*(ptr as *const _)),
            Op::OpConstantNullObject => Instruction::ConstantNullObject(&*(ptr as *const _)),
            Op::OpSpecConstantTrue => Instruction::SpecConstantTrue(&*(ptr as *const _)),
            Op::OpSpecConstantFalse => Instruction::SpecConstantFalse(&*(ptr as *const _)),
            Op::OpSpecConstant => Instruction::SpecConstant(&*(ptr as *const _)),
            Op::OpSpecConstantComposite => Instruction::SpecConstantComposite(&*(ptr as *const _)),
            Op::OpVariable => Instruction::Variable(&*(ptr as *const _)),
            Op::OpVariableArray => Instruction::VariableArray(&*(ptr as *const _)),
            Op::OpLoad => Instruction::Load(&*(ptr as *const _)),
            Op::OpStore => Instruction::Store(&*(ptr as *const _)),
            Op::OpCopyMemory => Instruction::CopyMemory(&*(ptr as *const _)),
            Op::OpCopyMemorySized => Instruction::CopyMemorySized(&*(ptr as *const _)),
            Op::OpAccessChain => Instruction::AccessChain(&*(ptr as *const _)),
            Op::OpInBoundsAccessChain => Instruction::InBoundsAccessChain(&*(ptr as *const _)),
            Op::OpArrayLength => Instruction::ArrayLength(&*(ptr as *const _)),
            Op::OpImagePointer => Instruction::ImagePointer(&*(ptr as *const _)),
            Op::OpGenericPtrMemSemantics => Instruction::GenericPtrMemSemantics(&*(ptr as *const _)),
            Op::OpFunction => Instruction::Function(&*(ptr as *const _)),
            Op::OpFunctionParameter => Instruction::FunctionParameter(&*(ptr as *const _)),
            Op::OpFunctionEnd => Instruction::FunctionEnd(&*(ptr as *const _)),
            Op::OpFunctionCall => Instruction::FunctionCall(&*(ptr as *const _)),
            Op::OpSampler => Instruction::Sampler(&*(ptr as *const _)),
            Op::OpTextureSample => Instruction::TextureSample(&*(ptr as *const _)),
            Op::OpTextureSampleDref => Instruction::TextureSampleDref(&*(ptr as *const _)),
            Op::OpTextureSampleLod => Instruction::TextureSampleLod(&*(ptr as *const _)),
            Op::OpTextureSampleProj => Instruction::TextureSampleProj(&*(ptr as *const _)),
            Op::OpTextureSampleGrad => Instruction::TextureSampleGrad(&*(ptr as *const _)),
            Op::OpTextureSampleOffset => Instruction::TextureSampleOffset(&*(ptr as *const _)),
            Op::OpTextureSampleProjLod => Instruction::TextureSampleProjLod(&*(ptr as *const _)),
            Op::OpTextureSampleProjGrad => Instruction::TextureSampleProjGrad(&*(ptr as *const _)),
            Op::OpTextureSampleLodOffset => Instruction::TextureSampleLodOffset(&*(ptr as *const _)),
            Op::OpTextureSampleProjOffset => Instruction::TextureSampleProjOffset(&*(ptr as *const _)),
            Op::OpTextureSampleGradOffset => Instruction::TextureSampleGradOffset(&*(ptr as *const _)),
            Op::OpTextureSampleProjLodOffset => Instruction::TextureSampleProjLodOffset(&*(ptr as *const _)),
            Op::OpTextureSampleProjGradOffset => Instruction::TextureSampleProjGradOffset(&*(ptr as *const _)),
            //Op::OpTextureFetchTexelLod => Instruction::TextureFetchTexelLod(&*(ptr as *const _)),
            Op::OpTextureFetchTexelOffset => Instruction::TextureFetchTexelOffset(&*(ptr as *const _)),
            Op::OpTextureFetchSample => Instruction::TextureFetchSample(&*(ptr as *const _)),
            Op::OpTextureFetchTexel => Instruction::TextureFetchTexel(&*(ptr as *const _)),
            Op::OpTextureGather => Instruction::TextureGather(&*(ptr as *const _)),
            Op::OpTextureGatherOffset => Instruction::TextureGatherOffset(&*(ptr as *const _)),
            Op::OpTextureGatherOffsets => Instruction::TextureGatherOffsets(&*(ptr as *const _)),
            Op::OpTextureQuerySizeLod => Instruction::TextureQuerySizeLod(&*(ptr as *const _)),
            Op::OpTextureQuerySize => Instruction::TextureQuerySize(&*(ptr as *const _)),
            Op::OpTextureQueryLod => Instruction::TextureQueryLod(&*(ptr as *const _)),
            Op::OpTextureQueryLevels => Instruction::TextureQueryLevels(&*(ptr as *const _)),
            Op::OpTextureQuerySamples => Instruction::TextureQuerySamples(&*(ptr as *const _)),
            Op::OpConvertFToU => Instruction::ConvertFToU(&*(ptr as *const _)),
            Op::OpConvertFToS => Instruction::ConvertFToS(&*(ptr as *const _)),
            Op::OpConvertSToF => Instruction::ConvertSToF(&*(ptr as *const _)),
            Op::OpConvertUToF => Instruction::ConvertUToF(&*(ptr as *const _)),
            Op::OpUConvert => Instruction::UConvert(&*(ptr as *const _)),
            Op::OpSConvert => Instruction::SConvert(&*(ptr as *const _)),
            Op::OpFConvert => Instruction::FConvert(&*(ptr as *const _)),
            Op::OpConvertPtrToU => Instruction::ConvertPtrToU(&*(ptr as *const _)),
            Op::OpConvertUToPtr => Instruction::ConvertUToPtr(&*(ptr as *const _)),
            Op::OpPtrCastToGeneric => Instruction::PtrCastToGeneric(&*(ptr as *const _)),
            Op::OpGenericCastToPtr => Instruction::GenericCastToPtr(&*(ptr as *const _)),
            Op::OpBitcast => Instruction::Bitcast(&*(ptr as *const _)),
            Op::OpGenericCastToPtrExplicit => Instruction::GenericCastToPtrExplicit(&*(ptr as *const _)),
            //Op::OpSatConvertSToU => Instruction::SatConvertSToU(&*(ptr as *const _)),
            //Op::OpSatConvertUToS => Instruction::SatConvertUToS(&*(ptr as *const _)),
            Op::OpVectorExtractDynamic => Instruction::VectorExtractDynamic(&*(ptr as *const _)),
            Op::OpVectorInsertDynamic => Instruction::VectorInsertDynamic(&*(ptr as *const _)),
            Op::OpVectorShuffle => Instruction::VectorShuffle(&*(ptr as *const _)),
            Op::OpCompositeConstruct => Instruction::CompositeConstruct(&*(ptr as *const _)),
            Op::OpCompositeExtract => Instruction::CompositeExtract(&*(ptr as *const _)),
            Op::OpCompositeInsert => Instruction::CompositeInsert(&*(ptr as *const _)),
            Op::OpCopyObject => Instruction::CopyObject(&*(ptr as *const _)),
            Op::OpTranspose => Instruction::Transpose(&*(ptr as *const _)),
            Op::OpSNegate => Instruction::SNegate(&*(ptr as *const _)),
            Op::OpFNegate => Instruction::FNegate(&*(ptr as *const _)),
            Op::OpNot => Instruction::Not(&*(ptr as *const _)),
            Op::OpIAdd => Instruction::IAdd(&*(ptr as *const _)),
            Op::OpFAdd => Instruction::FAdd(&*(ptr as *const _)),
            Op::OpISub => Instruction::ISub(&*(ptr as *const _)),
            Op::OpFSub => Instruction::FSub(&*(ptr as *const _)),
            Op::OpIMul => Instruction::IMul(&*(ptr as *const _)),
            Op::OpFMul => Instruction::FMul(&*(ptr as *const _)),
            Op::OpUDiv => Instruction::UDiv(&*(ptr as *const _)),
            Op::OpSDiv => Instruction::SDiv(&*(ptr as *const _)),
            Op::OpFDiv => Instruction::FDiv(&*(ptr as *const _)),
            Op::OpUMod => Instruction::UMod(&*(ptr as *const _)),
            Op::OpSRem => Instruction::SRem(&*(ptr as *const _)),
            Op::OpSMod => Instruction::SMod(&*(ptr as *const _)),
            Op::OpFRem => Instruction::FRem(&*(ptr as *const _)),
            Op::OpFMod => Instruction::FMod(&*(ptr as *const _)),
            Op::OpVectorTimesScalar => Instruction::VectorTimesScalar(&*(ptr as *const _)),
            Op::OpMatrixTimesScalar => Instruction::MatrixTimesScalar(&*(ptr as *const _)),
            Op::OpVectorTimesMatrix => Instruction::VectorTimesMatrix(&*(ptr as *const _)),
            Op::OpMatrixTimesVector => Instruction::MatrixTimesVector(&*(ptr as *const _)),
            Op::OpMatrixTimesMatrix => Instruction::MatrixTimesMatrix(&*(ptr as *const _)),
            Op::OpOuterProduct => Instruction::OuterProduct(&*(ptr as *const _)),
            Op::OpDot => Instruction::Dot(&*(ptr as *const _)),
            Op::OpShiftRightLogical => Instruction::ShiftRightLogical(&*(ptr as *const _)),
            Op::OpShiftRightArithmetic => Instruction::ShiftRightArithmetic(&*(ptr as *const _)),
            Op::OpShiftLeftLogical => Instruction::ShiftLeftLogical(&*(ptr as *const _)),
            Op::OpBitwiseOr => Instruction::BitwiseOr(&*(ptr as *const _)),
            Op::OpBitwiseXor => Instruction::BitwiseXor(&*(ptr as *const _)),
            Op::OpBitwiseAnd => Instruction::BitwiseAnd(&*(ptr as *const _)),
            Op::OpAny => Instruction::Any(&*(ptr as *const _)),
            Op::OpAll => Instruction::All(&*(ptr as *const _)),
            Op::OpIsNan => Instruction::IsNan(&*(ptr as *const _)),
            Op::OpIsInf => Instruction::IsInf(&*(ptr as *const _)),
            Op::OpIsFinite => Instruction::IsFinite(&*(ptr as *const _)),
            Op::OpIsNormal => Instruction::IsNormal(&*(ptr as *const _)),
            Op::OpSignBitSet => Instruction::SignBitSet(&*(ptr as *const _)),
            Op::OpLessOrGreater => Instruction::LessOrGreater(&*(ptr as *const _)),
            Op::OpOrdered => Instruction::Ordered(&*(ptr as *const _)),
            Op::OpUnordered => Instruction::Unordered(&*(ptr as *const _)),
            Op::OpLogicalOr => Instruction::LogicalOr(&*(ptr as *const _)),
            Op::OpLogicalXor => Instruction::LogicalXor(&*(ptr as *const _)),
            Op::OpLogicalAnd => Instruction::LogicalAnd(&*(ptr as *const _)),
            Op::OpSelect => Instruction::Select(&*(ptr as *const _)),
            Op::OpIEqual => Instruction::IEqual(&*(ptr as *const _)),
            Op::OpFOrdEqual => Instruction::FOrdEqual(&*(ptr as *const _)),
            Op::OpFUnordEqual => Instruction::FUnordEqual(&*(ptr as *const _)),
            Op::OpINotEqual => Instruction::INotEqual(&*(ptr as *const _)),
            Op::OpFOrdNotEqual => Instruction::FOrdNotEqual(&*(ptr as *const _)),
            Op::OpFUnordNotEqual => Instruction::FUnordNotEqual(&*(ptr as *const _)),
            Op::OpULessThan => Instruction::ULessThan(&*(ptr as *const _)),
            Op::OpSLessThan => Instruction::SLessThan(&*(ptr as *const _)),
            Op::OpFOrdLessThan => Instruction::FOrdLessThan(&*(ptr as *const _)),
            Op::OpFUnordLessThan => Instruction::FUnordLessThan(&*(ptr as *const _)),
            Op::OpUGreaterThan => Instruction::UGreaterThan(&*(ptr as *const _)),
            Op::OpSGreaterThan => Instruction::SGreaterThan(&*(ptr as *const _)),
            Op::OpFOrdGreaterThan => Instruction::FOrdGreaterThan(&*(ptr as *const _)),
            Op::OpFUnordGreaterThan => Instruction::FUnordGreaterThan(&*(ptr as *const _)),
            Op::OpULessThanEqual => Instruction::ULessThanEqual(&*(ptr as *const _)),
            Op::OpSLessThanEqual => Instruction::SLessThanEqual(&*(ptr as *const _)),
            Op::OpFOrdLessThanEqual => Instruction::FOrdLessThanEqual(&*(ptr as *const _)),
            Op::OpFUnordLessThanEqual => Instruction::FUnordLessThanEqual(&*(ptr as *const _)),
            Op::OpUGreaterThanEqual => Instruction::UGreaterThanEqual(&*(ptr as *const _)),
            Op::OpSGreaterThanEqual => Instruction::SGreaterThanEqual(&*(ptr as *const _)),
            Op::OpFOrdGreaterThanEqual => Instruction::FOrdGreaterThanEqual(&*(ptr as *const _)),
            Op::OpFUnordGreaterThanEqual => Instruction::FUnordGreaterThanEqual(&*(ptr as *const _)),
            Op::OpDPdx => Instruction::DPdx(&*(ptr as *const _)),
            Op::OpDPdy => Instruction::DPdy(&*(ptr as *const _)),
            Op::OpFwidth => Instruction::Fwidth(&*(ptr as *const _)),
            Op::OpDPdxFine => Instruction::DPdxFine(&*(ptr as *const _)),
            Op::OpDPdyFine => Instruction::DPdyFine(&*(ptr as *const _)),
            Op::OpFwidthFine => Instruction::FwidthFine(&*(ptr as *const _)),
            Op::OpDPdxCoarse => Instruction::DPdxCoarse(&*(ptr as *const _)),
            Op::OpDPdyCoarse => Instruction::DPdyCoarse(&*(ptr as *const _)),
            Op::OpFwidthCoarse => Instruction::FwidthCoarse(&*(ptr as *const _)),
            Op::OpPhi => Instruction::Phi(&*(ptr as *const _)),
            Op::OpLoopMerge => Instruction::LoopMerge(&*(ptr as *const _)),
            Op::OpSelectionMerge => Instruction::SelectionMerge(&*(ptr as *const _)),
            Op::OpLabel => Instruction::Label(&*(ptr as *const _)),
            Op::OpBranch => Instruction::Branch(&*(ptr as *const _)),
            Op::OpBranchConditional => Instruction::BranchConditional(&*(ptr as *const _)),
            Op::OpSwitch => Instruction::Switch(&*(ptr as *const _)),
            Op::OpKill => Instruction::Kill(&*(ptr as *const _)),
            Op::OpReturn => Instruction::Return(&*(ptr as *const _)),
            Op::OpReturnValue => Instruction::ReturnValue(&*(ptr as *const _)),
            Op::OpUnreachable => Instruction::Unreachable(&*(ptr as *const _)),
            Op::OpLifetimeStart => Instruction::LifetimeStart(&*(ptr as *const _)),
            Op::OpLifetimeStop => Instruction::LifetimeStop(&*(ptr as *const _)),
            Op::OpAtomicInit => Instruction::AtomicInit(&*(ptr as *const _)),
            Op::OpAtomicLoad => Instruction::AtomicLoad(&*(ptr as *const _)),
            Op::OpAtomicStore => Instruction::AtomicStore(&*(ptr as *const _)),
            Op::OpAtomicExchange => Instruction::AtomicExchange(&*(ptr as *const _)),
            Op::OpAtomicCompareExchange => Instruction::AtomicCompareExchange(&*(ptr as *const _)),
            Op::OpAtomicCompareExchangeWeak => Instruction::AtomicCompareExchangeWeak(&*(ptr as *const _)),
            Op::OpAtomicIIncrement => Instruction::AtomicIIncrement(&*(ptr as *const _)),
            Op::OpAtomicIDecrement => Instruction::AtomicIDecrement(&*(ptr as *const _)),
            Op::OpAtomicIAdd => Instruction::AtomicIAdd(&*(ptr as *const _)),
            Op::OpAtomicISub => Instruction::AtomicISub(&*(ptr as *const _)),
            Op::OpAtomicUMin => Instruction::AtomicUMin(&*(ptr as *const _)),
            Op::OpAtomicUMax => Instruction::AtomicUMax(&*(ptr as *const _)),
            Op::OpAtomicAnd => Instruction::AtomicAnd(&*(ptr as *const _)),
            Op::OpAtomicOr => Instruction::AtomicOr(&*(ptr as *const _)),
            Op::OpAtomicXor => Instruction::AtomicXor(&*(ptr as *const _)),
            //Op::OpAtomicIMin => Instruction::AtomicIMin(&*(ptr as *const _)),
            //Op::OpAtomicIMax => Instruction::AtomicIMax(&*(ptr as *const _)),
            Op::OpEmitVertex => Instruction::EmitVertex(&*(ptr as *const _)),
            Op::OpEndPrimitive => Instruction::EndPrimitive(&*(ptr as *const _)),
            Op::OpEmitStreamVertex => Instruction::EmitStreamVertex(&*(ptr as *const _)),
            Op::OpEndStreamPrimitive => Instruction::EndStreamPrimitive(&*(ptr as *const _)),
            Op::OpControlBarrier => Instruction::ControlBarrier(&*(ptr as *const _)),
            Op::OpMemoryBarrier => Instruction::MemoryBarrier(&*(ptr as *const _)),
            Op::OpAsyncGroupCopy => Instruction::AsyncGroupCopy(&*(ptr as *const _)),
            Op::OpWaitGroupEvents => Instruction::WaitGroupEvents(&*(ptr as *const _)),
            Op::OpGroupAll => Instruction::GroupAll(&*(ptr as *const _)),
            Op::OpGroupAny => Instruction::GroupAny(&*(ptr as *const _)),
            Op::OpGroupBroadcast => Instruction::GroupBroadcast(&*(ptr as *const _)),
            Op::OpGroupIAdd => Instruction::GroupIAdd(&*(ptr as *const _)),
            Op::OpGroupFAdd => Instruction::GroupFAdd(&*(ptr as *const _)),
            Op::OpGroupFMin => Instruction::GroupFMin(&*(ptr as *const _)),
            Op::OpGroupUMin => Instruction::GroupUMin(&*(ptr as *const _)),
            Op::OpGroupSMin => Instruction::GroupSMin(&*(ptr as *const _)),
            Op::OpGroupFMax => Instruction::GroupFMax(&*(ptr as *const _)),
            Op::OpGroupUMax => Instruction::GroupUMax(&*(ptr as *const _)),
            Op::OpGroupSMax => Instruction::GroupSMax(&*(ptr as *const _)),
            Op::OpEnqueueMarker => Instruction::EnqueueMarker(&*(ptr as *const _)),
            Op::OpEnqueueKernel => Instruction::EnqueueKernel(&*(ptr as *const _)),
            Op::OpGetKernelNDrangeSubGroupCount => Instruction::GetKernelNDrangeSubGroupCount(&*(ptr as *const _)),
            Op::OpGetKernelNDrangeMaxSubGroupSize => Instruction::GetKernelNDrangeMaxSubGroupSize(&*(ptr as *const _)),
            Op::OpGetKernelWorkGroupSize => Instruction::GetKernelWorkGroupSize(&*(ptr as *const _)),
            Op::OpGetKernelPreferredWorkGroupSizeMultiple => Instruction::GetKernelPreferredWorkGroupSizeMultiple(&*(ptr as *const _)),
            Op::OpRetainEvent => Instruction::RetainEvent(&*(ptr as *const _)),
            Op::OpReleaseEvent => Instruction::ReleaseEvent(&*(ptr as *const _)),
            Op::OpCreateUserEvent => Instruction::CreateUserEvent(&*(ptr as *const _)),
            Op::OpIsValidEvent => Instruction::IsValidEvent(&*(ptr as *const _)),
            Op::OpSetUserEventStatus => Instruction::SetUserEventStatus(&*(ptr as *const _)),
            Op::OpCaptureEventProfilingInfo => Instruction::CaptureEventProfilingInfo(&*(ptr as *const _)),
            Op::OpGetDefaultQueue => Instruction::GetDefaultQueue(&*(ptr as *const _)),
            Op::OpBuildNDRange => Instruction::BuildNDRange(&*(ptr as *const _)),
            Op::OpReadPipe => Instruction::ReadPipe(&*(ptr as *const _)),
            Op::OpWritePipe => Instruction::WritePipe(&*(ptr as *const _)),
            Op::OpReservedReadPipe => Instruction::ReservedReadPipe(&*(ptr as *const _)),
            Op::OpReservedWritePipe => Instruction::ReservedWritePipe(&*(ptr as *const _)),
            Op::OpReserveReadPipePackets => Instruction::ReserveReadPipePackets(&*(ptr as *const _)),
            Op::OpReserveWritePipePackets => Instruction::ReserveWritePipePackets(&*(ptr as *const _)),
            Op::OpCommitReadPipe => Instruction::CommitReadPipe(&*(ptr as *const _)),
            Op::OpCommitWritePipe => Instruction::CommitWritePipe(&*(ptr as *const _)),
            Op::OpIsValidReserveId => Instruction::IsValidReserveId(&*(ptr as *const _)),
            Op::OpGetNumPipePackets => Instruction::GetNumPipePackets(&*(ptr as *const _)),
            Op::OpGetMaxPipePackets => Instruction::GetMaxPipePackets(&*(ptr as *const _)),
            Op::OpGroupReserveReadPipePackets => Instruction::GroupReserveReadPipePackets(&*(ptr as *const _)),
            Op::OpGroupReserveWritePipePackets => Instruction::GroupReserveWritePipePackets(&*(ptr as *const _)),
            Op::OpGroupCommitReadPipe => Instruction::GroupCommitReadPipe(&*(ptr as *const _)),
            Op::OpGroupCommitWritePipe => Instruction::GroupCommitWritePipe(&*(ptr as *const _)),
            Op::OpLastValue => unreachable!()
        }
    }
}
